### PR TITLE
Fixed Readme - config.neon

### PR DESCRIPTION
**Pull request by landsman**

### CODE REVIEW

**Comment by enumag** [comment]
It's correct, Zenify/DoctrineMigrations 3.0-beta uses Arachne/EventDispatcher instead.

**Comment by landsman** [comment]
Without this change I was saw message:
Class 'Arachne\ContainerAdapter\DI\ContainerAdapterExtension' not found

Composer:
"zenify/doctrine-migrations": "^2.3",

**Comment by enumag** [comment]
Yeah. Change composer to

```
"zenify/doctrine-migrations": "^3.0",
```

**Comment by landsman** [comment]
thanks

**Pull request closed without merging**
