### PR TITLE
Lazy load of migration classes

### PR DESCRIPTION
**Pull request by fprochazka**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you describe motivation?

**Comment by fprochazka** [comment]
When I list the console commands, all the migration classes all loaded. Even tho they're not going to be used. 1) That's wrong 2) There is no reason for it.

**Comment by TomasVotruba** [comment]
Do you have some non-opinion based arguments? Like speed improvements or similar.

**Comment by fprochazka** [comment]
Once you have >100 migrations, that's wasting time to load >100 files and wasting memory to create >2*100 objects.
What kind of benchmarks do you want? That's basic common sense. 

I was expecting you to ask me for tests which I was lazy to write, not explain why not loading hundreds of objects to memory is better than loading them if they're not going to be used.

**Comment by TomasVotruba** [comment]
I think it's premature optimization, when not based on real use case. Code complexity rises for no reason.
We're using around 100 migrations with >60 MB of size and the bottleneck is always the speed of database.

I also think this should be resolved on Console level, not in every command.

**Comment by fprochazka** [comment]
I started writing the lazy loading, because I had an error in one of the migration classes (the name didn't match the filename, because I was mesing with it) and the entire console became completely dead (exceptions all over). I think that it's stupid to kill the entire console app, just because I have one filename wrong. Kill the migration commands? Yes, that makes sense, the migration is broken. Kill starting of workers or crons that are completely unrelated? This is not C this is PHP.

> I also think this should be resolved once on console level, not in every command-based package.

Actually, Kdyby\Console tries to solve that. If you use `@inject` properties on your commands, it disabled autowiring to them and only calls `callInjects` when you run the command.
Maybe a service proxy could also solve that.

**Comment by TomasVotruba** [comment]
How did you managed to create wrong migration name? It can be created by console commands.

I thing solving wrong naming by lazy loading is workaround, that doesn't really solve the issue. Just allows it to exists silently.

> Maybe a service proxy could also solve that in this case.

Not sure how that's would look like. Do you mean in console level?

---

Btw, what are these `getCs`/`setCs`? Looks like some another issue you've. Maybe we could separate PR and solve it easily.

**Comment by TomasVotruba** [comment]
After some time, I think this might be useful feature. The PR should be sent to `doctrine/migrations` repository though.

**Comment by TomasVotruba** [comment]
@fprochazka  As for console lazy loading, this might be interesting source http://mmoreram.com/blog/2015/05/08/lazy-commands-in-symfony/

**Comment by TomasVotruba** [comment]
I'll try to push this into origin repo.

**Comment by TomasVotruba** [comment]
Oh, just found out it's supported ("just enough" solution) since: https://github.com/doctrine/migrations/pull/238

**Comment by TomasVotruba** [comment]
Resolved via https://github.com/Zenify/DoctrineMigrations/commit/bd61d88b5184067579c05e0ab2161e431a2c2782

**Pull request closed without merging**
