### PR TITLE
Readded support for PHP 5.4

### PR DESCRIPTION
**Pull request by enumag**
WIP: need to fix tests and travis

I'd like to use this package but unfortunately I still need PHP 5.4 support. Do I have to fork or would you be willing to merge this?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Version 1.0.0 should be PHP 5.4 compatible, isn't it?
Is there some bug?

I do not have time to provide legacy support properly (tried, failed), so all Zenify targets 5.5 as min.

**Comment by enumag** [comment]
Is 1.0.0 compatible with Nette 2.3? According to releases Nette 2.3 compatibility was added in version 2.1.0.

**Comment by TomasVotruba** [comment]
Dunno, please try it.

**Comment by mdjimy** [comment]
@enumag Could you please also fix test files? (ie. ``tests/DI/MigrationsExtensionTest.php``)

**Comment by TomasVotruba** [comment]
I move Zenify to [actively supported PHP versions](http://php.net/supported-versions.php).
For my reasons [see discussion](https://github.com/Zenify/DoctrineFixtures/commit/2b84150b765201726003438c581d714acd96e64a#commitcomment-12102862).


If you really need both PHP 5.4 and present version features, [use this fork](https://github.com/enumag/DoctrineMigrations/tree/php-54).

**Pull request closed without merging**
